# Generated by Django 5.2.4 on 2025-07-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevChApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='cupos_disponibles',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ruta',
            name='pasajeros',
            field=models.ManyToManyField(blank=True, related_name='rutas_como_pasajero', to='DevChApp.usuario'),
        ),
    ]
